#!/bin/bash      

#Color Variables

NC='\e[0m'
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
WHITE='\e[1;37m'
ORANGE='\e[0;33m'
BLUE='\e[0;34m'
PURPLE='\e[0;35m'
CYAN='\e[0;36m'
YELLOW='\e[1;33m'
DARGRAY='\e[1;30m'

#Lighter Colors
LIGRAY='\e[0;37m'
LIGREEN='\e[1;32m'
LIRED='\e[1;31m'
LIBLUE='\e[1;34m'
LIPURPLE='\e[1;35m'
LICYAN='\e[1;36m'


#Background Color Variables

BACKBLACK='\e[0;40m'
BACKRED='\e[0;41m'
BACKGREEN='\e[0;42m'
BACKWHITE='\e[1;47m'
BACKORANGE='\e[0;43m'
BACKBLUE='\e[0;44m'
BACKPURPLE='\e[0;45m'
BACKCYAN='\e[0;46m'
BACKYELLOW='\e[1;43m'

#Lighter Colors
BACKLIGRAY='\e[0;47m'
BACKLIGREEN='\e[1;42m'
BACKLIRED='\e[1;41m'
BACKLIBLUE='\e[1;44m'
BACKLIPURPLE='\e[1;45m'
BACKLICYAN='\e[1;46m'

#Markup Variables
UNDERLINE='\e[4m'
BOLD='\e[1m'
BLINK='\e[5m'
REVVID='\e[7m'


echo -e "${CYAN}${BOLD}\nWelcome to Adam's Update Script!\n${NC}"

if [ "$1" == "snaps" ]; then
   echo -e "${WHITE}Checking for snap updates. Please Wait...${NC}"
   sudo snap refresh
    else
if [ "$1" = "pi-apps" ]; then
    $HOME/pi-apps/updater cli
else
    sudo apt update
    sudo apt -y --allow-downgrades upgrade $1
    if [ "$2" == "easter-egg" ]; then
        echo -e "${LIPURPLE}${BOLD}\nThis update script has super cow powers!${NC}"
fi
fi
fi
echo -e "${GREEN}\nDone!${NC}"
