#!/bin/bash      

#Color Variables

NC='\e[0m'
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
WHITE='\e[1;37m'
ORANGE='\e[0;33m'
BLUE='\e[0;34m'
PURPLE='\e[0;35m'
CYAN='\e[0;36m'
YELLOW='\e[1;33m'
DARGRAY='\e[1;30m'

#Lighter Colors
LIGRAY='\e[0;37m'
LIGREEN='\e[1;32m'
LIRED='\e[1;31m'
LIBLUE='\e[1;34m'
LIPURPLE='\e[1;35m'
LICYAN='\e[1;36m'


#Background Color Variables

BACKBLACK='\e[0;40m'
BACKRED='\e[0;41m'
BACKGREEN='\e[0;42m'
BACKWHITE='\e[1;47m'
BACKORANGE='\e[0;43m'
BACKBLUE='\e[0;44m'
BACKPURPLE='\e[0;45m'
BACKCYAN='\e[0;46m'
BACKYELLOW='\e[1;43m'

#Lighter Colors
BACKLIGRAY='\e[0;47m'
BACKLIGREEN='\e[1;42m'
BACKLIRED='\e[1;41m'
BACKLIBLUE='\e[1;44m'
BACKLIPURPLE='\e[1;45m'
BACKLICYAN='\e[1;46m'

#Markup Variables
UNDERLINE='\e[4m'
BOLD='\e[1m'
BLINK='\e[5m'
REVVID='\e[7m'

printf "${CYAN}${BOLD}\nWelcome to Crilum's Update Script!\n${NC}"

if [ "$1" == "help" ]; then

   printf "\n${WHITE}Usage: ${CYAN}${BOLD}update${NC} ${YELLOW}${BOLD}ARGS${NC}${WHITE}\n\nThese are the available arguments for ${CYAN}${BOLD}update${NC}${WHITE}:\n\n${CYAN}${BOLD}update${NC} - ${WHITE}Updates apps with Apt\n${CYAN}${BOLD}update ${YELLOW}${BOLD}all${NC} - ${WHITE}Updates apps on all supported systems\n${CYAN}${BOLD}update${NC} ${YELLOW}${BOLD}pi-apps${NC} - ${WHITE}Updates apps with Pi-Apps\n${CYAN}${BOLD}update${NC} ${YELLOW}${BOLD}snaps${NC} - ${WHITE}Updates snaps with snapd\n${CYAN}${BOLD}update${NC} ${YELLOW}${BOLD}flatpak${NC} - ${WHITE}Update flatpak build instances${NC}\n${CYAN}${BOLD}update ${YELLOW}${BOLD}self-update${NC} - ${WHITE}Updates the ${CYAN}${BOLD}update ${WHITE}script\n${CYAN}${BOLD}update${NC} ${YELLOW}${BOLD}help${NC} - ${WHITE}Displays this help\n"
elif [ "$1" == "all" ]; then 
    printf "\n\n${WHITE}Apt output:${NC}\n\n"
    sudo apt update
    sudo apt -y upgrade
    sudo apt -y autoremove
    printf "\n\n${WHITE}Pi-Apps output:${NC}\n"
    ~/pi-apps/updater cli-yes
    printf "\n${WHITE}npm output:${NC}\n"
    npm update | grep -v npm WARN npm npm does not support Node.js v10.24.0 npm WARN npm You should probably upgrade to a newer version of node as we npm WARN npm "can't" make any promises that npm will work with this version. 
    printf "\n\n${WHITE}Flatpak output:${NC}\n"
    flatpak update
    printf "\n${WHITE}\nChecking for snap updates. Please Wait...${NC}\n\n"
    sudo snap refresh
elif [ "$1" == "self-update" ]; then
   printf "\n${WHITE}Starting Self-Update...${NC}\n\n"
   curl "https://raw.githubusercontent.com/Crilum/update-app-script/main/install" | sudo bash
elif [ "$1" = "snaps" ]; then
   printf "${WHITE}\nChecking for snap updates. Please Wait...${NC}\n\n"
   sudo snap refresh
   
elif [ "$1" = "pi-apps" ]; then
    printf "\n${WHITE}Pi-Apps output:${NC}\n"
    ~/pi-apps/updater cli-yes
elif [ "$1" == "flatpak" ]; then
   printf "\n${WHITE}Flatpak output:${NC}\n"
   flatpak update
elif [ "$1" == "npm" ]; then
   printf "\n${WHITE}npm output:${NC}\n"
   npm update
else
    printf "\n${WHITE}Apt output:${NC}\n\n"
    sudo apt update
    sudo apt -y upgrade $1
    sudo apt -y autoremove
fi

if [ "$2" = "easter-egg" ]; then
        printf "${LIPURPLE}${BOLD}\nThis update script has super cow powers!\n${NC}"
fi

printf "${GREEN}\nDone!\n${NC}"
